project:
  title: ""
  type: website

website:
  page-navigation: true
  repo-url: https://github.com/cboettig/quarto-material
  repo-actions: [edit, issue]
#"#1A237E"
  navbar:
    background: "dark"
    foreground: "#f8f9fa"
    left:
      - file: index.qmd
        icon: house-door-fill
        text: home
      - file: about.qmd
        icon: book
    tools:
      - icon: github
        href: https://github.com/
        aria-label: GitHub

  # Sidebar requires layout as full or article, not 'custom'
  sidebar:
    style: "floating"
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - about.qmd
    tools:
      - icon: github
        href: https://github.com/
        aria-label: GitHub


format:
  html:
    page-layout: custom # change to full for narrower layout, see https://quarto.org/docs/output-formats/page-layout.html
    css:
      - assets/css/nucleo-icons.css
      - assets/css/quarto-material-kit.css
      - assets/css/custom.css
    include-after-body: [assets/html/footer.html]
    title-block-banner: assets/img/bg3.jpg
    title-block-mask: '<span class="mask bg-gradient-light opacity-2"></span>'
    template: assets/partials/html.template
#    template-partials:
#      - assets/partials/title-block.html
#      - assets/partials/toc.html


