project:
  title: ""
  type: website

website:
  page-navigation: true
  repo-url: https://github.com/cboettig/quarto-material
  repo-actions: [edit, issue]

  navbar:
    background: "#1A237E"
    foreground: "#f8f9fa"
    contents:
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/
        aria-label: GitHub

format:
  html:
    page-layout: custom
    css:
      - assets/css/nucleo-icons.css
      - assets/css/quarto-material-kit.css
      - assets/css/custom.css
    include-after-body: [assets/html/footer.html]
    title-block-banner: assets/img/bg3.jpg
    template: assets/partials/html.template
#    template-partials:
#      - assets/partials/title-block.html
#      - assets/partials/toc.html


