project:
  title: "quarto-project-template"
  type: website

website:
  page-navigation: true
  repo-url: https://github.com/cboettig/quarto-material
  repo-actions: [edit, issue]

  navbar:
    background: primary
    search: true

format:
  html:
    theme: [yeti]
    css: [assets/css/material-kit.css]
    include-after-body: [assets/html/footer.html]

