project:
  title: ""
  type: website

website:
  page-navigation: true
  repo-url: https://github.com/cboettig/quarto-material
  repo-actions: [edit, issue]

  sidebar:
    background: "#1A237E"
    foreground: "#f8f9fa"
    contents:
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/
        aria-label: GitHub

format:
  html:
#    theme: [assets/scss/quarto-material-kit.scss]
    css: [assets/css/nucleo-icons.css, assets/css/quarto-material-kit.css]
    include-after-body: [assets/html/footer.html]

